// PrimitiveMeshTexts.cs
// 図形生成パネル用ローカライズ辞書
// Runtime/Poly_Ling_Player/View/PrimitiveMesh/ に配置

using System.Collections.Generic;
using Poly_Ling.Localization;

namespace Poly_Ling.Player
{
    public static class PrimitiveMeshTexts
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
        {
            ["PanelTitle"]    = new() { ["en"] = "Create Primitive", ["ja"] = "図形生成",         ["hi"] = "かたちをつくる" },
            ["Cube"]          = new() { ["en"] = "Cube",        ["ja"] = "直方体",      ["hi"] = "はこ" },
            ["Sphere"]        = new() { ["en"] = "Sphere",      ["ja"] = "球体",        ["hi"] = "たま" },
            ["Cylinder"]      = new() { ["en"] = "Cylinder",    ["ja"] = "円柱",        ["hi"] = "つつ" },
            ["Capsule"]       = new() { ["en"] = "Capsule",     ["ja"] = "カプセル",    ["hi"] = "カプセル" },
            ["Plane"]         = new() { ["en"] = "Plane",       ["ja"] = "平面",        ["hi"] = "ひらたい" },
            ["Pyramid"]       = new() { ["en"] = "Pyramid",     ["ja"] = "角錐",        ["hi"] = "かくすい" },
            ["Revolution"]    = new() { ["en"] = "Revolution",  ["ja"] = "回転体",      ["hi"] = "かいてんたい" },
            ["Profile2D"]     = new() { ["en"] = "Profile2D",   ["ja"] = "2D押し出し",  ["hi"] = "おしだし" },
            ["NohMask"]       = new() { ["en"] = "NohMask",     ["ja"] = "能面",        ["hi"] = "のうめん" },
            ["Name"]          = new() { ["en"] = "Name",        ["ja"] = "名前",        ["hi"] = "なまえ" },
            ["Size"]          = new() { ["en"] = "Size",        ["ja"] = "サイズ",      ["hi"] = "おおきさ" },
            ["Segments"]      = new() { ["en"] = "Segments",    ["ja"] = "分割数",      ["hi"] = "ぶんかつ" },
            ["WidthX"]        = new() { ["en"] = "Width (X)",   ["ja"] = "幅 (X)",      ["hi"] = "はば" },
            ["HeightY"]       = new() { ["en"] = "Height (Y)",  ["ja"] = "高さ (Y)",    ["hi"] = "たかさ" },
            ["DepthZ"]        = new() { ["en"] = "Depth (Z)",   ["ja"] = "奥行き (Z)",  ["hi"] = "おくゆき" },
            ["Radius"]        = new() { ["en"] = "Radius",      ["ja"] = "半径",        ["hi"] = "はんけい" },
            ["RadiusTop"]     = new() { ["en"] = "Radius Top",  ["ja"] = "上部半径",    ["hi"] = "うえのはんけい" },
            ["RadiusBottom"]  = new() { ["en"] = "Radius Bot",  ["ja"] = "下部半径",    ["hi"] = "したのはんけい" },
            ["Height"]        = new() { ["en"] = "Height",      ["ja"] = "高さ",        ["hi"] = "たかさ" },
            ["Radial"]        = new() { ["en"] = "Radial",      ["ja"] = "周方向",      ["hi"] = "まわり" },
            ["Lateral"]       = new() { ["en"] = "Lateral",     ["ja"] = "縦方向",      ["hi"] = "たてほうこう" },
            ["Cap"]           = new() { ["en"] = "Cap Seg",     ["ja"] = "キャップ分割", ["hi"] = "ふたぶんかつ" },
            ["CapTop"]        = new() { ["en"] = "Cap Top",     ["ja"] = "上キャップ",  ["hi"] = "うえのふた" },
            ["CapBottom"]     = new() { ["en"] = "Cap Bottom",  ["ja"] = "下キャップ",  ["hi"] = "したのふた" },
            ["Width"]         = new() { ["en"] = "Width",       ["ja"] = "幅",          ["hi"] = "はば" },
            ["DoubleSided"]   = new() { ["en"] = "Double Sided",["ja"] = "両面",        ["hi"] = "りょうめん" },
            ["Orientation"]   = new() { ["en"] = "Plane",       ["ja"] = "向き",        ["hi"] = "むき" },
            ["Sides"]         = new() { ["en"] = "Sides",       ["ja"] = "辺数",        ["hi"] = "へんすう" },
            ["BaseRadius"]    = new() { ["en"] = "Base Radius", ["ja"] = "底面半径",    ["hi"] = "そこのはんけい" },
            ["ApexOffset"]    = new() { ["en"] = "Apex Offset", ["ja"] = "頂点ずれ",    ["hi"] = "ちょうてんずれ" },
            ["CornerRadius"]  = new() { ["en"] = "Corner R",    ["ja"] = "角丸半径",    ["hi"] = "かどまる" },
            ["CornerSeg"]     = new() { ["en"] = "Corner Seg",  ["ja"] = "角丸分割",    ["hi"] = "かどぶんかつ" },
            ["CubeSphere"]    = new() { ["en"] = "CubeSphere",  ["ja"] = "キューブ球",  ["hi"] = "キューブきゅう" },
            ["Subdivisions"]  = new() { ["en"] = "Subdivisions",["ja"] = "分割数",      ["hi"] = "ぶんかつ" },
            ["SubdivX"]       = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["SubdivY"]       = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["SubdivZ"]       = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["LinkWHD"]       = new() { ["en"] = "Link W/H/D",  ["ja"] = "幅高奥連動",  ["hi"] = "れんどう" },
            ["LinkTopBottom"] = new() { ["en"] = "Link Top/Bot",["ja"] = "上下連動",    ["hi"] = "じょうげれんどう" },
            ["EdgeRadius"]    = new() { ["en"] = "Edge Radius", ["ja"] = "エッジ丸め",  ["hi"] = "えっじまる" },
            ["EdgeSeg"]       = new() { ["en"] = "Edge Seg",    ["ja"] = "エッジ分割",  ["hi"] = "えっじぶんかつ" },
            ["PivotOffset"]   = new() { ["en"] = "Pivot Offset",["ja"] = "ピボット",    ["hi"] = "ちゅうしん" },
            ["PivotX"]        = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["PivotY"]        = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["PivotZ"]        = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["Bottom"]        = new() { ["en"] = "Bottom",      ["ja"] = "下",          ["hi"] = "した" },
            ["Center"]        = new() { ["en"] = "Center",      ["ja"] = "中央",        ["hi"] = "まんなか" },
            ["Top"]           = new() { ["en"] = "Top",         ["ja"] = "上",          ["hi"] = "うえ" },
            ["WorldPos"]      = new() { ["en"] = "World Position",["ja"] = "ワールド座標",["hi"] = "ざひょう" },
            ["WorldPosX"]     = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["WorldPosY"]     = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["WorldPosZ"]     = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["IgnorePose"]    = new() { ["en"] = "Ignore Pose (Armature)", ["ja"] = "姿勢無視(アーマチャ)", ["hi"] = "しせいむし" },
            ["UpperSphere"]   = new() { ["en"] = "Upper Sphere",           ["ja"] = "上球",                  ["hi"] = "うえのたま" },
            ["LowerSphere"]   = new() { ["en"] = "Lower Sphere",           ["ja"] = "下球",                  ["hi"] = "したのたま" },
            ["Create"]        = new() { ["en"] = "Create",      ["ja"] = "生成",        ["hi"] = "つくる" },
            ["NotSupported"]  = new() { ["en"] = "Not supported in Player build", ["ja"] = "Playerビルドでは未対応", ["hi"] = "みたいおう" },
            ["VertsFaces"]    = new() { ["en"] = "V:{0}  F:{1}", ["ja"] = "頂点:{0}  面:{1}", ["hi"] = "てん:{0}  めん:{1}" },

            // ── Revolution ──────────────────────────────────────────────
            ["RadialSegments"]   = new() { ["en"] = "Radial Segments", ["ja"] = "周方向分割数",     ["hi"] = "まわりのぶんかつすう" },
            ["CloseTop"]         = new() { ["en"] = "Close Top",       ["ja"] = "上部を閉じる",     ["hi"] = "うえをとじる" },
            ["CloseBottom"]      = new() { ["en"] = "Close Bottom",    ["ja"] = "下部を閉じる",     ["hi"] = "したをとじる" },
            ["CloseLoop"]        = new() { ["en"] = "Close Loop",      ["ja"] = "ループを閉じる",   ["hi"] = "わっかをとじる" },
            ["Spiral"]           = new() { ["en"] = "Spiral",          ["ja"] = "らせん",           ["hi"] = "らせん" },
            ["SpiralTurns"]      = new() { ["en"] = "Turns",           ["ja"] = "回転数",           ["hi"] = "かいてんすう" },
            ["SpiralPitch"]      = new() { ["en"] = "Pitch",           ["ja"] = "ピッチ",           ["hi"] = "ピッチ" },
            ["FlipY"]            = new() { ["en"] = "Flip Y",          ["ja"] = "Y反転",            ["hi"] = "Yはんてん" },
            ["FlipZ"]            = new() { ["en"] = "Flip Z",          ["ja"] = "Z反転",            ["hi"] = "Zはんてん" },
            ["Preset"]           = new() { ["en"] = "Preset",          ["ja"] = "プリセット",       ["hi"] = "プリセット" },
            ["Custom"]           = new() { ["en"] = "Custom",          ["ja"] = "カスタム",         ["hi"] = "カスタム" },
            ["Donut"]            = new() { ["en"] = "Donut",           ["ja"] = "ドーナツ",         ["hi"] = "ドーナツ" },
            ["RoundedPipe"]      = new() { ["en"] = "Rounded Pipe",    ["ja"] = "角丸パイプ",       ["hi"] = "まるパイプ" },
            ["Vase"]             = new() { ["en"] = "Vase",            ["ja"] = "花瓶",             ["hi"] = "かびん" },
            ["Goblet"]           = new() { ["en"] = "Goblet",          ["ja"] = "ゴブレット",       ["hi"] = "コップ" },
            ["Bell"]             = new() { ["en"] = "Bell",            ["ja"] = "釣鐘",             ["hi"] = "かね" },
            ["Hourglass"]        = new() { ["en"] = "Hourglass",       ["ja"] = "砂時計",           ["hi"] = "すなどけい" },
            ["DonutMajorRadius"] = new() { ["en"] = "Major Radius",    ["ja"] = "外径",             ["hi"] = "そとのおおきさ" },
            ["DonutMinorRadius"] = new() { ["en"] = "Minor Radius",    ["ja"] = "断面半径",         ["hi"] = "だんめんのはんけい" },
            ["DonutTubeSegs"]    = new() { ["en"] = "Tube Segments",   ["ja"] = "チューブ分割数",   ["hi"] = "チューブのぶんかつすう" },
            ["PipeInnerRadius"]  = new() { ["en"] = "Inner Radius",    ["ja"] = "内径",             ["hi"] = "うちのおおきさ" },
            ["PipeOuterRadius"]  = new() { ["en"] = "Outer Radius",    ["ja"] = "外径",             ["hi"] = "そとのおおきさ" },
            ["PipeHeight"]       = new() { ["en"] = "Height",          ["ja"] = "高さ",             ["hi"] = "たかさ" },
            ["InnerCorner"]      = new() { ["en"] = "Inner Corner",    ["ja"] = "内角",             ["hi"] = "うちのかど" },
            ["OuterCorner"]      = new() { ["en"] = "Outer Corner",    ["ja"] = "外角",             ["hi"] = "そとのかど" },
            ["ProfileEditor"]    = new() { ["en"] = "Profile Editor",  ["ja"] = "プロファイル編集", ["hi"] = "プロファイル" },
            ["AddPoint"]         = new() { ["en"] = "Add Point",    ["ja"] = "点追加",   ["hi"] = "てんついか" },
            ["InsertPoint"]      = new() { ["en"] = "Insert Point", ["ja"] = "点の挿入", ["hi"] = "てんそうにゅう" },
            ["P2dEditorHelp"]    = new() { ["en"] = "Click edge: insert point / Drag vertex: move", ["ja"] = "エッジクリック: 点挿入 / 頂点ドラッグ: 移動", ["hi"] = "せんクリック: てんついか / ドラッグ: いどう" },

            // ── 下絵 ─────────────────────────────────────────────────────
            ["BgImage"]    = new() { ["en"] = "Background Image",  ["ja"] = "下絵",         ["hi"] = "したえ" },
            ["BgLoad"]     = new() { ["en"] = "Load",              ["ja"] = "読込",         ["hi"] = "よみこむ" },
            ["BgClear"]    = new() { ["en"] = "Clear",             ["ja"] = "クリア",       ["hi"] = "クリア" },
            ["BgAlpha"]    = new() { ["en"] = "Opacity",           ["ja"] = "不透明度",     ["hi"] = "ふとうめいど" },
            ["BgMoveMode"] = new() { ["en"] = "Move/Scale Mode",   ["ja"] = "移動/拡縮モード", ["hi"] = "いどう/かくしゅくモード" },
            ["DeletePoint"]      = new() { ["en"] = "Delete Point",    ["ja"] = "点削除",           ["hi"] = "てんさくじょ" },
            ["ClearProfile"]     = new() { ["en"] = "Clear",           ["ja"] = "クリア",           ["hi"] = "クリア" },

            // ── Profile2D ───────────────────────────────────────────────
            ["Scale"]            = new() { ["en"] = "Scale",           ["ja"] = "スケール",         ["hi"] = "おおきさ" },
            ["Offset"]           = new() { ["en"] = "Offset",          ["ja"] = "オフセット",       ["hi"] = "ずれ" },
            ["OffsetX"]          = new() { ["en"] = "Offset X",        ["ja"] = "オフセット X",     ["hi"] = "ずれX" },
            ["OffsetY"]          = new() { ["en"] = "Offset Y",        ["ja"] = "オフセット Y",     ["hi"] = "ずれY" },
            ["Thickness"]        = new() { ["en"] = "Thickness",       ["ja"] = "厚み",             ["hi"] = "あつみ" },
            ["EdgeSettings"]     = new() { ["en"] = "Edge Settings",   ["ja"] = "角処理",           ["hi"] = "かどのせってい" },
            ["FrontSegments"]    = new() { ["en"] = "Front Segs",      ["ja"] = "前面分割",         ["hi"] = "まえのぶんかつ" },
            ["BackSegments"]     = new() { ["en"] = "Back Segs",       ["ja"] = "背面分割",         ["hi"] = "うしろのぶんかつ" },
            ["EdgeSize"]         = new() { ["en"] = "Size",            ["ja"] = "サイズ",           ["hi"] = "おおきさ" },
            ["EdgeInward"]       = new() { ["en"] = "Outward Keep Face",["ja"] = "外向き面保持",    ["hi"] = "そとむきめん" },
            ["Loops"]            = new() { ["en"] = "Loops",           ["ja"] = "ループ",           ["hi"] = "ループ" },
            ["AddLoop"]          = new() { ["en"] = "Add Loop",        ["ja"] = "ループ追加",       ["hi"] = "ループついか" },
            ["RemoveLoop"]       = new() { ["en"] = "Remove",          ["ja"] = "削除",             ["hi"] = "さくじょ" },
            ["IsHole"]           = new() { ["en"] = "Hole",            ["ja"] = "穴",               ["hi"] = "あな" },
            ["LoadCSV"]          = new() { ["en"] = "Load CSV",        ["ja"] = "CSV読込",          ["hi"] = "CSVよみこむ" },
            ["SaveCSV"]          = new() { ["en"] = "Save CSV",        ["ja"] = "CSV保存",          ["hi"] = "CSVほぞん" },
            ["NoFile"]           = new() { ["en"] = "(no file)",       ["ja"] = "(未選択)",         ["hi"] = "(みせんたく)" },
            ["LoopSides"]        = new() { ["en"] = "Sides",           ["ja"] = "辺数",             ["hi"] = "へんすう" },

            // ── NohMask ─────────────────────────────────────────────────
            ["Landmarks"]        = new() { ["en"] = "Landmarks JSON",  ["ja"] = "ランドマークJSON", ["hi"] = "ランドマーク" },
            ["TrianglesJson"]    = new() { ["en"] = "Triangles JSON",  ["ja"] = "三角形JSON",       ["hi"] = "さんかくけい" },
            ["FaceIndex"]        = new() { ["en"] = "Face Index",      ["ja"] = "顔インデックス",   ["hi"] = "かおばんごう" },
            ["DepthScale"]       = new() { ["en"] = "Depth Scale",     ["ja"] = "奥行きスケール",   ["hi"] = "おくゆき" },
            ["FlipFaces"]        = new() { ["en"] = "Flip Faces",      ["ja"] = "面を反転",         ["hi"] = "うらがえす" },
            ["NotSelected"]      = new() { ["en"] = "(not selected)",  ["ja"] = "(未選択)",         ["hi"] = "(みせんたく)" },
        };

        public static string T(string key) => L.GetFrom(Texts, key);
        public static string T(string key, params object[] args) => L.GetFrom(Texts, key, args);
    }
}
