// PrimitiveMeshTexts.cs
// 図形生成パネル用ローカライズ辞書
// Runtime/Poly_Ling_Player/View/PrimitiveMesh/ に配置

using System.Collections.Generic;
using Poly_Ling.Localization;

namespace Poly_Ling.Player
{
    public static class PrimitiveMeshTexts
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
        {
            ["PanelTitle"]    = new() { ["en"] = "Create Primitive", ["ja"] = "図形生成",         ["hi"] = "かたちをつくる" },
            ["Cube"]          = new() { ["en"] = "Cube",        ["ja"] = "直方体",      ["hi"] = "はこ" },
            ["Sphere"]        = new() { ["en"] = "Sphere",      ["ja"] = "球体",        ["hi"] = "たま" },
            ["Cylinder"]      = new() { ["en"] = "Cylinder",    ["ja"] = "円柱",        ["hi"] = "つつ" },
            ["Capsule"]       = new() { ["en"] = "Capsule",     ["ja"] = "カプセル",    ["hi"] = "カプセル" },
            ["Plane"]         = new() { ["en"] = "Plane",       ["ja"] = "平面",        ["hi"] = "ひらたい" },
            ["Pyramid"]       = new() { ["en"] = "Pyramid",     ["ja"] = "角錐",        ["hi"] = "かくすい" },
            ["Revolution"]    = new() { ["en"] = "Revolution",  ["ja"] = "回転体",      ["hi"] = "かいてんたい" },
            ["Profile2D"]     = new() { ["en"] = "Profile2D",   ["ja"] = "2D押し出し",  ["hi"] = "おしだし" },
            ["NohMask"]       = new() { ["en"] = "NohMask",     ["ja"] = "能面",        ["hi"] = "のうめん" },
            ["Frill"]         = new() { ["en"] = "Frill",       ["ja"] = "フリル",      ["hi"] = "フリル" },
            ["Pipe"]          = new() { ["en"] = "Pipe",        ["ja"] = "パイプ",      ["hi"] = "パイプ" },
            ["PlaceObject"]   = new() { ["en"] = "Place Obj",   ["ja"] = "藤壺（オブジェクト配置）",        ["hi"] = "ぶったいをおく" },
            ["PlaceScale"]    = new() { ["en"] = "Scale",       ["ja"] = "配置スケール", ["hi"] = "おおきさ" },
            ["PlaceRoll"]     = new() { ["en"] = "Z Roll",      ["ja"] = "Zロール",     ["hi"] = "Zまわりのかいてん" },
            ["PlaceRollHint"] = new() { ["en"] = "Rotates each placed object around the rung normal (Z) in 90-degree steps.",
                                          ["ja"] = "配置物を rung 法線（Z軸）まわりに 90 度単位で回します。0 / 90 / 180 / 270。",
                                          ["hi"] = "おいたものを Zじくのまわりに 90どずつ まわします。" },
            ["PlaceIncludeChildren"]     = new() { ["en"] = "Include Children", ["ja"] = "子オブジェクトも含める", ["hi"] = "こもふくめる" },
            ["PlaceIncludeChildrenHint"] = new() { ["en"] = "Treats each checked object as a root and places its descendants together.", ["ja"] = "チェックしたオブジェクトをルートとみなし、その子孫も一緒に配置します。", ["hi"] = "えらんだものの したにあるものも いっしょにおきます。" },
            ["ObjectArray"]   = new() { ["en"] = "Obj Array",   ["ja"] = "歪み複製",    ["hi"] = "ゆがみふくせい" },
            ["Text"]          = new() { ["en"] = "Text",        ["ja"] = "文字",        ["hi"] = "もじ" },
            ["Bridge"]        = new() { ["en"] = "Bridge",      ["ja"] = "ブリッジ",    ["hi"] = "あなつなぎ" },
            ["Ribbon"]        = new() { ["en"] = "Ribbon",      ["ja"] = "リボン",      ["hi"] = "リボン" },
            ["NGonGear"]      = new() { ["en"] = "Gear (Simple)", ["ja"] = "簡易歯車",    ["hi"] = "かんたんはぐるま" },
            ["NGonStar"]      = new() { ["en"] = "Star",        ["ja"] = "スター",      ["hi"] = "ほし" },
            ["InvoluteGear"]  = new() { ["en"] = "Involute Gear", ["ja"] = "インボリュート歯車", ["hi"] = "はぐるま" },
            ["BridgeHint"]    = new() { ["en"] = "Select one vertex or edge on each hole, import them, then create faces between the two rims.",
                                          ["ja"] = "2つの穴それぞれで頂点1個または辺1本を選んで取り込み、縁どうしに面を張ります。",
                                          ["hi"] = "2つのあなで てんかへんを1つずつえらんでとりこみ、めんをはります。" },
            ["BridgeHoleA"]   = new() { ["en"] = "Hole A",      ["ja"] = "穴A",         ["hi"] = "あなA" },
            ["BridgeHoleB"]   = new() { ["en"] = "Hole B",      ["ja"] = "穴B",         ["hi"] = "あなB" },
            ["BridgeImport"]  = new() { ["en"] = "Import from selection", ["ja"] = "選択から取り込み", ["hi"] = "えらんだのをとりこむ" },
            ["BridgeImportBoth"] = new() { ["en"] = "Import A/B at once", ["ja"] = "A/B 同時取り込み", ["hi"] = "AとBをいっぺんにとりこむ" },
            ["BridgeImportBothHint"] = new() { ["en"] = "Fills hole A and hole B from one selection. If the selection covers only one hole, only A is filled.",
                                          ["ja"] = "1回の選択から穴A と 穴B を埋めます。選択が1つの穴にしか掛かっていないときは穴A だけを埋めます。",
                                          ["hi"] = "いっかいのせんたくで あなAとあなBをうめます。あなが1つなら あなAだけ。" },
            ["BridgeNotSet"]  = new() { ["en"] = "(not set)",   ["ja"] = "(未取り込み)", ["hi"] = "(まだ)" },
            // 生成物の行き先は共通の「追加先」(AddMode) に一本化した。
            // 穴つなぎ専用の「書き込み先」トグルは廃止。
            ["BridgeAddModeHint"] = new() { ["en"] = "Add to Existing Object: writes into the object chosen in the name box. New Object: created as a child of the hole A object (or of whichever candidate is closer to the root). Vertices from the other object are cloned by position.",
                                          ["ja"] = "「既存の描画オブジェクトに追加」は名前欄で選んだオブジェクトへ書き込みます。「新しい描画オブジェクト」は穴A物体の子として作ります（穴A物体と穴B物体に子孫関係があるときはルートに近い側の子）。書き込み先でない側の穴の頂点は位置クローンを作ります。",
                                          ["hi"] = "「きそんについか」は なまえらんでえらんだものにかきます。「あたらしいオブジェクト」は あなAのこにします。べつのオブジェクトのあなは いちだけコピーします。" },
            ["BridgeFlipPair"] = new() { ["en"] = "Flip correspondence", ["ja"] = "対応フリップ", ["hi"] = "むきをかえる" },
            ["BridgeFlipFaces"] = new() { ["en"] = "Flip faces", ["ja"] = "面フリップ",  ["hi"] = "めんをうらがえす" },
            ["BridgeSubdiv"]  = new() { ["en"] = "Subdivisions", ["ja"] = "分割数",      ["hi"] = "ぶんかつ" },
            ["BridgeNeedBoth"] = new() { ["en"] = "Import both holes first.", ["ja"] = "穴A と 穴B を取り込んでください", ["hi"] = "あなAとあなBをとりこんでください" },
            ["BridgeNoMesh"]  = new() { ["en"] = "Mesh not found.", ["ja"] = "メッシュが見つかりません", ["hi"] = "メッシュがない" },
            ["BridgeNoPick"]  = new() { ["en"] = "Selection is not available.", ["ja"] = "選択を取得できません", ["hi"] = "えらんだものがとれない" },
            ["BridgeNoTarget"] = new() { ["en"] = "Add target is not configured.", ["ja"] = "追加先が設定されていません", ["hi"] = "ついかさきがない" },
            ["TextFont"]      = new() { ["en"] = "Font",        ["ja"] = "フォント",    ["hi"] = "フォント" },
            ["TextFontReload"] = new() { ["en"] = "Reload Fonts", ["ja"] = "フォント再読込", ["hi"] = "よみなおす" },
            ["TextNoFont"]    = new() { ["en"] = "(no font found)", ["ja"] = "(フォント未検出)", ["hi"] = "(フォントがない)" },
            ["TextFontDir"]   = new() { ["en"] = "Folders with fonts.txt use it; folders without one are scanned for .plgly.",
                                          ["ja"] = "fonts.txt があればそれを使い、無ければ .plgly を探します。",
                                          ["hi"] = "フォントをおくばしょ。fonts.txt がなければ .plgly をさがします。" },
            ["TextFontDirs"]  = new() { ["en"] = "Font Folders", ["ja"] = "フォント置き場", ["hi"] = "フォントのばしょ" },
            ["TextFontDirAdd"] = new() { ["en"] = "Add Folder",  ["ja"] = "フォルダを追加", ["hi"] = "ばしょをふやす" },
            ["TextFontDirReset"] = new() { ["en"] = "Reset to Default", ["ja"] = "既定に戻す", ["hi"] = "もとにもどす" },
            ["TextString"]    = new() { ["en"] = "Text",        ["ja"] = "文字列",      ["hi"] = "もじれつ" },
            ["TextStringHint"] = new() { ["en"] = "A line break starts a new line.",
                                          ["ja"] = "改行すると行が増えます",
                                          ["hi"] = "かいぎょうすると ぎょうがふえます" },
            ["TextLetterSpacing"] = new() { ["en"] = "Letter Sp", ["ja"] = "字間",       ["hi"] = "もじのあいだ" },
            ["TextLineSpacing"]   = new() { ["en"] = "Line Sp",   ["ja"] = "行間",       ["hi"] = "ぎょうのあいだ" },
            ["TextGlyphs"]    = new() { ["en"] = "glyphs",      ["ja"] = "収録字数",    ["hi"] = "もじのかず" },
            ["TextMissing"]   = new() { ["en"] = "Not in font:", ["ja"] = "未収録の文字:", ["hi"] = "ないもじ:" },
            ["Name"]          = new() { ["en"] = "Name",        ["ja"] = "名前",        ["hi"] = "なまえ" },
            ["Size"]          = new() { ["en"] = "Size",        ["ja"] = "サイズ",      ["hi"] = "おおきさ" },
            ["Segments"]      = new() { ["en"] = "Segments",    ["ja"] = "分割数",      ["hi"] = "ぶんかつ" },
            ["WidthX"]        = new() { ["en"] = "Width (X)",   ["ja"] = "幅 (X)",      ["hi"] = "はば" },
            ["HeightY"]       = new() { ["en"] = "Height (Y)",  ["ja"] = "高さ (Y)",    ["hi"] = "たかさ" },
            ["DepthZ"]        = new() { ["en"] = "Depth (Z)",   ["ja"] = "奥行き (Z)",  ["hi"] = "おくゆき" },
            ["Radius"]        = new() { ["en"] = "Radius",      ["ja"] = "半径",        ["hi"] = "はんけい" },
            ["RadiusTop"]     = new() { ["en"] = "Radius Top",  ["ja"] = "上部半径",    ["hi"] = "うえのはんけい" },
            ["RadiusBottom"]  = new() { ["en"] = "Radius Bot",  ["ja"] = "下部半径",    ["hi"] = "したのはんけい" },
            ["Height"]        = new() { ["en"] = "Height",      ["ja"] = "高さ",        ["hi"] = "たかさ" },
            ["Radial"]        = new() { ["en"] = "Radial",      ["ja"] = "周方向",      ["hi"] = "まわり" },
            ["Lateral"]       = new() { ["en"] = "Lateral",     ["ja"] = "縦方向",      ["hi"] = "たてほうこう" },
            ["Cap"]           = new() { ["en"] = "Cap Seg",     ["ja"] = "キャップ分割", ["hi"] = "ふたぶんかつ" },
            ["CapTop"]        = new() { ["en"] = "Cap Top",     ["ja"] = "上キャップ",  ["hi"] = "うえのふた" },
            ["CapBottom"]     = new() { ["en"] = "Cap Bottom",  ["ja"] = "下キャップ",  ["hi"] = "したのふた" },
            ["Width"]         = new() { ["en"] = "Width",       ["ja"] = "幅",          ["hi"] = "はば" },
            ["DoubleSided"]   = new() { ["en"] = "Double Sided",["ja"] = "両面",        ["hi"] = "りょうめん" },
            ["FaceFront"]     = new() { ["en"] = "Face Front",  ["ja"] = "正面向き",    ["hi"] = "しょうめんむき" },
            ["Orientation"]   = new() { ["en"] = "Plane",       ["ja"] = "向き",        ["hi"] = "むき" },
            ["PivotCentroid"] = new() { ["en"] = "Centroid",    ["ja"] = "重心",        ["hi"] = "じゅうしん" },
            ["PlaneXY"]       = new() { ["en"] = "XY plane",    ["ja"] = "XY平面上に生成", ["hi"] = "XYへいめん" },
            ["PlaneXZ"]       = new() { ["en"] = "XZ plane",    ["ja"] = "XZ平面上に生成", ["hi"] = "XZへいめん" },
            ["PlaneYZ"]       = new() { ["en"] = "YZ plane",    ["ja"] = "YZ平面上に生成", ["hi"] = "YZへいめん" },
            ["Sides"]         = new() { ["en"] = "Sides",       ["ja"] = "辺数",        ["hi"] = "へんすう" },
            ["BaseRadius"]    = new() { ["en"] = "Base Radius", ["ja"] = "底面半径",    ["hi"] = "そこのはんけい" },
            ["ApexOffset"]    = new() { ["en"] = "Apex Offset", ["ja"] = "頂点ずれ",    ["hi"] = "ちょうてんずれ" },
            ["CornerRadius"]  = new() { ["en"] = "Corner R",    ["ja"] = "角丸半径",    ["hi"] = "かどまる" },
            ["CornerSeg"]     = new() { ["en"] = "Corner Seg",  ["ja"] = "角丸分割",    ["hi"] = "かどぶんかつ" },
            ["CubeSphere"]    = new() { ["en"] = "CubeSphere",  ["ja"] = "キューブ球",  ["hi"] = "キューブきゅう" },
            ["Subdivisions"]  = new() { ["en"] = "Subdivisions",["ja"] = "分割数",      ["hi"] = "ぶんかつ" },
            ["SubdivX"]       = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["SubdivY"]       = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["SubdivZ"]       = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["LinkWHD"]       = new() { ["en"] = "Link W/H/D",  ["ja"] = "幅高奥連動",  ["hi"] = "れんどう" },
            ["LinkTopBottom"] = new() { ["en"] = "Link Top/Bot",["ja"] = "上下連動",    ["hi"] = "じょうげれんどう" },
            ["EdgeRadius"]    = new() { ["en"] = "Edge Radius", ["ja"] = "エッジ丸め",  ["hi"] = "えっじまる" },
            ["EdgeSeg"]       = new() { ["en"] = "Edge Seg",    ["ja"] = "エッジ分割",  ["hi"] = "えっじぶんかつ" },
            ["PivotOffset"]   = new() { ["en"] = "Object Center (Pivot)",["ja"] = "描画オブジェクトの中心（ピボット位置）",["hi"] = "ちゅうしん" },
            ["PivotX"]        = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["PivotY"]        = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["PivotZ"]        = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["Bottom"]        = new() { ["en"] = "Bottom",      ["ja"] = "下",          ["hi"] = "した" },
            ["Center"]        = new() { ["en"] = "Center",      ["ja"] = "中央",        ["hi"] = "まんなか" },
            ["Top"]           = new() { ["en"] = "Top",         ["ja"] = "上",          ["hi"] = "うえ" },
            ["WorldPos"]      = new() { ["en"] = "World Position",["ja"] = "ワールド座標",["hi"] = "ざひょう" },
            ["WorldPosX"]     = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["WorldPosY"]     = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["WorldPosZ"]     = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["ObjectPose"]    = new() { ["en"] = "Object Pose",["ja"] = "描画オブジェクトの姿勢",["hi"] = "むきとおおきさ" },
            ["Material"]      = new() { ["en"] = "Material",    ["ja"] = "マテリアル",  ["hi"] = "しつかん" },
            ["MaterialNone"]  = new() { ["en"] = "(created on generate)",
                                          ["ja"] = "（無し・生成時に作成）",
                                          ["hi"] = "なし・つくります" },
            ["Bake"]          = new() { ["en"] = "Bake",        ["ja"] = "ベイク",      ["hi"] = "やきこみ" },
            ["Rotation"]      = new() { ["en"] = "Rotation (deg)", ["ja"] = "回転 (度)",   ["hi"] = "まわす" },
            ["RotX"]          = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["RotY"]          = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["RotZ"]          = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["ScaleLabel"]    = new() { ["en"] = "Scale",       ["ja"] = "スケール",     ["hi"] = "おおきさばい" },
            ["ScaleX"]        = new() { ["en"] = "X",           ["ja"] = "X",           ["hi"] = "X" },
            ["ScaleY"]        = new() { ["en"] = "Y",           ["ja"] = "Y",           ["hi"] = "Y" },
            ["ScaleZ"]        = new() { ["en"] = "Z",           ["ja"] = "Z",           ["hi"] = "Z" },
            ["TrsReset"]      = new() { ["en"] = "Reset Pos/Rot/Scale", ["ja"] = "座標・回転・スケールをリセット", ["hi"] = "もとにもどす" },
            ["PlaceGizmo"]       = new() { ["en"] = "Place Gizmo",  ["ja"] = "配置ギズモ",     ["hi"] = "おくときのギズモ" },
            ["PlaceGizmoMove"]   = new() { ["en"] = "Move",         ["ja"] = "配置:移動",      ["hi"] = "うごかす" },
            ["PlaceGizmoRotate"] = new() { ["en"] = "Rotate",       ["ja"] = "配置:回転",      ["hi"] = "まわす" },
            ["PlaceGizmoScale"]  = new() { ["en"] = "Scale",        ["ja"] = "配置:スケール",  ["hi"] = "おおきさ" },
            ["MergeDuplicates"] = new() { ["en"] = "Merge Duplicate Vertices", ["ja"] = "重複頂点をマージ", ["hi"] = "てんをまとめる" },
            ["UpperSphere"]   = new() { ["en"] = "Upper Sphere",           ["ja"] = "上球",                  ["hi"] = "うえのたま" },
            ["LowerSphere"]   = new() { ["en"] = "Lower Sphere",           ["ja"] = "下球",                  ["hi"] = "したのたま" },
            ["Create"]        = new() { ["en"] = "Create",      ["ja"] = "生成",        ["hi"] = "つくる" },
            ["NotSupported"]  = new() { ["en"] = "Not supported in Player build", ["ja"] = "Playerビルドでは未対応", ["hi"] = "みたいおう" },
            ["VertsFaces"]    = new() { ["en"] = "V:{0}  F:{1}", ["ja"] = "頂点:{0}  面:{1}", ["hi"] = "てん:{0}  めん:{1}" },

            // ── Revolution ──────────────────────────────────────────────
            ["RadialSegments"]   = new() { ["en"] = "Radial Segments", ["ja"] = "周方向分割数",     ["hi"] = "まわりのぶんかつすう" },
            ["CloseTop"]         = new() { ["en"] = "Close Top",       ["ja"] = "上部を閉じる",     ["hi"] = "うえをとじる" },
            ["CloseBottom"]      = new() { ["en"] = "Close Bottom",    ["ja"] = "下部を閉じる",     ["hi"] = "したをとじる" },
            ["CloseLoop"]        = new() { ["en"] = "Close Loop",      ["ja"] = "ループを閉じる",   ["hi"] = "わっかをとじる" },
            ["Spiral"]           = new() { ["en"] = "Spiral",          ["ja"] = "らせん",           ["hi"] = "らせん" },
            ["SpiralTurns"]      = new() { ["en"] = "Turns",           ["ja"] = "回転数",           ["hi"] = "かいてんすう" },
            ["SpiralPitch"]      = new() { ["en"] = "Pitch",           ["ja"] = "ピッチ",           ["hi"] = "ピッチ" },
            ["FlipY"]            = new() { ["en"] = "Flip Y",          ["ja"] = "Y反転",            ["hi"] = "Yはんてん" },
            ["FlipZ"]            = new() { ["en"] = "Flip Z",          ["ja"] = "Z反転",            ["hi"] = "Zはんてん" },
            ["Preset"]           = new() { ["en"] = "Preset",          ["ja"] = "プリセット",       ["hi"] = "プリセット" },
            ["Custom"]           = new() { ["en"] = "Custom",          ["ja"] = "カスタム",         ["hi"] = "カスタム" },
            ["Donut"]            = new() { ["en"] = "Donut",           ["ja"] = "ドーナツ",         ["hi"] = "ドーナツ" },
            ["RoundedPipe"]      = new() { ["en"] = "Rounded Pipe",    ["ja"] = "角丸パイプ",       ["hi"] = "まるパイプ" },
            ["Vase"]             = new() { ["en"] = "Vase",            ["ja"] = "花瓶",             ["hi"] = "かびん" },
            ["Goblet"]           = new() { ["en"] = "Goblet",          ["ja"] = "ゴブレット",       ["hi"] = "コップ" },
            ["Bell"]             = new() { ["en"] = "Bell",            ["ja"] = "釣鐘",             ["hi"] = "かね" },
            ["Hourglass"]        = new() { ["en"] = "Hourglass",       ["ja"] = "砂時計",           ["hi"] = "すなどけい" },
            ["DonutMajorRadius"] = new() { ["en"] = "Major Radius",    ["ja"] = "外径",             ["hi"] = "そとのおおきさ" },
            ["DonutMinorRadius"] = new() { ["en"] = "Minor Radius",    ["ja"] = "断面半径",         ["hi"] = "だんめんのはんけい" },
            ["DonutTubeSegs"]    = new() { ["en"] = "Tube Segments",   ["ja"] = "チューブ分割数",   ["hi"] = "チューブのぶんかつすう" },
            ["PipeInnerRadius"]  = new() { ["en"] = "Inner Radius",    ["ja"] = "内径",             ["hi"] = "うちのおおきさ" },
            ["PipeOuterRadius"]  = new() { ["en"] = "Outer Radius",    ["ja"] = "外径",             ["hi"] = "そとのおおきさ" },
            ["PipeHeight"]       = new() { ["en"] = "Height",          ["ja"] = "高さ",             ["hi"] = "たかさ" },
            ["InnerCorner"]      = new() { ["en"] = "Inner Corner",    ["ja"] = "内角",             ["hi"] = "うちのかど" },
            ["OuterCorner"]      = new() { ["en"] = "Outer Corner",    ["ja"] = "外角",             ["hi"] = "そとのかど" },
            ["ProfileEditor"]    = new() { ["en"] = "2D Profile Editor", ["ja"] = "2Dプロファイル編集", ["hi"] = "2Dプロファイルへんしゅう" },
            ["EditTools"]        = new() { ["en"] = "Edit Tools",     ["ja"] = "編集ツール",       ["hi"] = "へんしゅうツール" },
            ["SelectionTransform"] = new() { ["en"] = "Move / Scale / Rotate Selected Points", ["ja"] = "選択点の移動など", ["hi"] = "せんたくてんのいどうなど" },
            ["Magnet"]           = new() { ["en"] = "Magnet (Proportional Edit)", ["ja"] = "マグネット（比例編集）", ["hi"] = "マグネット" },
            ["AnchorSection"]    = new() { ["en"] = "Rotate / Scale Anchor (2D Pivot) Position", ["ja"] = "回転/拡大縮小アンカー（2D回転中心）位置", ["hi"] = "かいてんのちゅうしん" },
            ["ProfileCsvSection"] = new() { ["en"] = "Profile CSV", ["ja"] = "プロファイル用CSV", ["hi"] = "プロファイルのCSV" },
            ["AddPoint"]         = new() { ["en"] = "Add Point",    ["ja"] = "点追加",   ["hi"] = "てんついか" },
            ["InsertPoint"]      = new() { ["en"] = "Insert Point", ["ja"] = "点の挿入", ["hi"] = "てんそうにゅう" },
            ["P2dEditorHelp"]    = new() { ["en"] = "Click edge: insert point / Drag vertex: move", ["ja"] = "エッジクリック: 点挿入 / 頂点ドラッグ: 移動", ["hi"] = "せんクリック: てんついか / ドラッグ: いどう" },

            // ── 下絵 ─────────────────────────────────────────────────────
            ["BgImage"]    = new() { ["en"] = "Background Image",  ["ja"] = "下絵",         ["hi"] = "したえ" },
            ["BgLoad"]     = new() { ["en"] = "Load",              ["ja"] = "読込",         ["hi"] = "よみこむ" },
            ["BgClear"]    = new() { ["en"] = "Clear",             ["ja"] = "クリア",       ["hi"] = "クリア" },
            ["BgAlpha"]    = new() { ["en"] = "Opacity",           ["ja"] = "不透明度",     ["hi"] = "ふとうめいど" },
            ["BgMoveMode"] = new() { ["en"] = "Move/Scale Mode",   ["ja"] = "移動/拡縮モード", ["hi"] = "いどう/かくしゅくモード" },
            ["DeletePoint"]      = new() { ["en"] = "Delete Point",    ["ja"] = "点削除",           ["hi"] = "てんさくじょ" },
            ["ClearProfile"]     = new() { ["en"] = "Clear",           ["ja"] = "クリア",           ["hi"] = "クリア" },

            // ── Profile2D ───────────────────────────────────────────────
            ["Scale"]            = new() { ["en"] = "Scale",           ["ja"] = "スケール",         ["hi"] = "おおきさ" },
            ["Offset"]           = new() { ["en"] = "Offset",          ["ja"] = "オフセット",       ["hi"] = "ずれ" },
            ["OffsetX"]          = new() { ["en"] = "Offset X",        ["ja"] = "オフセット X",     ["hi"] = "ずれX" },
            ["OffsetY"]          = new() { ["en"] = "Offset Y",        ["ja"] = "オフセット Y",     ["hi"] = "ずれY" },
            ["Thickness"]        = new() { ["en"] = "Thickness",       ["ja"] = "厚み",             ["hi"] = "あつみ" },
            ["EdgeSettings"]     = new() { ["en"] = "Edge Settings",   ["ja"] = "角処理",           ["hi"] = "かどのせってい" },
            ["FrontSegments"]    = new() { ["en"] = "Front Segs",      ["ja"] = "前面分割",         ["hi"] = "まえのぶんかつ" },
            ["BackSegments"]     = new() { ["en"] = "Back Segs",       ["ja"] = "背面分割",         ["hi"] = "うしろのぶんかつ" },
            ["EdgeSize"]         = new() { ["en"] = "Size",            ["ja"] = "サイズ",           ["hi"] = "おおきさ" },
            ["EdgeInward"]       = new() { ["en"] = "Outward Keep Face",["ja"] = "外向き面保持",    ["hi"] = "そとむきめん" },
            ["SymmetryMode"]     = new() { ["en"] = "Symmetry (X)",     ["ja"] = "左右対称",         ["hi"] = "さゆうたいしょう" },
            ["Loops"]            = new() { ["en"] = "Loops",           ["ja"] = "ループ",           ["hi"] = "ループ" },
            ["AddLoop"]          = new() { ["en"] = "Add Loop",        ["ja"] = "ループ追加",       ["hi"] = "ループついか" },
            ["RemoveLoop"]       = new() { ["en"] = "Remove",          ["ja"] = "削除",             ["hi"] = "さくじょ" },
            ["IsHole"]           = new() { ["en"] = "Hole",            ["ja"] = "穴",               ["hi"] = "あな" },
            ["LoadCSV"]          = new() { ["en"] = "Load CSV",        ["ja"] = "CSV読込",          ["hi"] = "CSVよみこむ" },
            ["Browse"]           = new() { ["en"] = "Browse…",        ["ja"] = "参照…",            ["hi"] = "さがす" },
            ["SelectAllLoop"]    = new() { ["en"] = "Select Loop",    ["ja"] = "ループを選択",     ["hi"] = "ループをせんたく" },
            ["DuplicateLoop"]    = new() { ["en"] = "Duplicate Loop", ["ja"] = "ループ複製",       ["hi"] = "ループふくせい" },
            ["FlipLoopH"]        = new() { ["en"] = "Flip Loop H",    ["ja"] = "ループを左右反転", ["hi"] = "ループをさゆうはんてん" },
            ["SaveCSV"]          = new() { ["en"] = "Save CSV",        ["ja"] = "CSV保存",          ["hi"] = "CSVほぞん" },
            ["NoFile"]           = new() { ["en"] = "(no file)",       ["ja"] = "(未選択)",         ["hi"] = "(みせんたく)" },
            ["LoopSides"]        = new() { ["en"] = "Sides",           ["ja"] = "辺数",             ["hi"] = "へんすう" },
            ["ShowGizmo"]        = new() { ["en"] = "Gizmo",           ["ja"] = "ギズモ表示",       ["hi"] = "ギズモひょうじ" },
            ["ShowVertices"]     = new() { ["en"] = "Vertices",        ["ja"] = "頂点表示",         ["hi"] = "てんひょうじ" },

            // ── NohMask ─────────────────────────────────────────────────
            ["Landmarks"]        = new() { ["en"] = "Landmarks JSON",  ["ja"] = "ランドマークJSON", ["hi"] = "ランドマーク" },
            ["TrianglesJson"]    = new() { ["en"] = "Triangles JSON",  ["ja"] = "三角形JSON",       ["hi"] = "さんかくけい" },
            ["FaceIndex"]        = new() { ["en"] = "Face Index",      ["ja"] = "顔インデックス",   ["hi"] = "かおばんごう" },
            ["DepthScale"]       = new() { ["en"] = "Depth Scale",     ["ja"] = "奥行きスケール",   ["hi"] = "おくゆき" },
            ["FlipFaces"]        = new() { ["en"] = "Flip Faces",      ["ja"] = "面を反転",         ["hi"] = "うらがえす" },
            ["FlipX"]            = new() { ["en"] = "Flip X",          ["ja"] = "X軸反転",          ["hi"] = "Xはんてん" },
            ["FlipY"]            = new() { ["en"] = "Flip Y",          ["ja"] = "Y軸反転",          ["hi"] = "Yはんてん" },
            ["FlipZ"]            = new() { ["en"] = "Flip Z",          ["ja"] = "Z軸反転",          ["hi"] = "Zはんてん" },
            ["FillHoles"]        = new() { ["en"] = "Fill Holes",      ["ja"] = "穴を埋める",       ["hi"] = "あなをうめる" },
            ["RimEnabled"]       = new() { ["en"] = "Rim (wings)",     ["ja"] = "外縁を拡張(羽根)", ["hi"] = "はねをつける" },
            ["RimWidth"]         = new() { ["en"] = "Rim Width",       ["ja"] = "羽根の幅",         ["hi"] = "はねのはば" },
            ["NotSelected"]      = new() { ["en"] = "(not selected)",  ["ja"] = "(未選択)",         ["hi"] = "(みせんたく)" },
            ["BuiltinDefault"]   = new() { ["en"] = "(built-in default)", ["ja"] = "(内蔵デフォルト)", ["hi"] = "(ないぞう)" },
            ["UseBuiltinDefault"]= new() { ["en"] = "Use built-in default", ["ja"] = "内蔵デフォルトを使用", ["hi"] = "ないぞうをつかう" },

            // ── 追加先モード ─────────────────────────────────────────────
            ["AddMode"]         = new() { ["en"] = "Add Target",             ["ja"] = "追加先",                         ["hi"] = "ついかさき" },
            ["AddModeNewObj"]   = new() { ["en"] = "New Object (default)",   ["ja"] = "新しい描画オブジェクト（デフォルト）", ["hi"] = "あたらしいオブジェクト" },
            ["AddModeExisting"] = new() { ["en"] = "Add to Existing Object", ["ja"] = "既存の描画オブジェクトに追加",         ["hi"] = "きそんについか" },
            ["AddModeNewModel"] = new() { ["en"] = "New Model",              ["ja"] = "新しいモデルを作って追加",             ["hi"] = "あたらしいモデル" },

            // ── メッシュ⇄プロファイル連携 ───────────────────────────────
            ["MeshProfileIO"]   = new() { ["en"] = "Import / Export Drawn Object", ["ja"] = "描画オブジェクトのインポートエクスポート", ["hi"] = "オブジェクトのやりとり" },
            ["ImportFromMesh"]  = new() { ["en"] = "Import from Mesh",   ["ja"] = "取り込み(メッシュ→)", ["hi"] = "とりこみ" },
            ["ApplyToMesh"]     = new() { ["en"] = "Apply to Mesh",      ["ja"] = "反映(→メッシュ)",    ["hi"] = "はんえい" },
            ["ImportedPoints"]  = new() { ["en"] = "Imported {0} pts",   ["ja"] = "取り込み: {0}点",     ["hi"] = "とりこみ: {0}てん" },
            ["ImportedLoops"]   = new() { ["en"] = "Imported {0} loops", ["ja"] = "取り込み: {0}ループ",  ["hi"] = "とりこみ: {0}ループ" },
            ["NoSelectedMesh"]  = new() { ["en"] = "No selected mesh",   ["ja"] = "選択メッシュなし",    ["hi"] = "えらんでない" },
            ["NoLinesFound"]    = new() { ["en"] = "No line segments",   ["ja"] = "線分が見つからない",  ["hi"] = "せんぶんなし" },
            ["AppliedToMesh"]   = new() { ["en"] = "Applied: {0} lines", ["ja"] = "反映: 線分{0}",       ["hi"] = "はんえい: せん{0}" },

            // ── フリル ──────────────────────────────────────────────────
            ["FrillBase"]       = new() { ["en"] = "Base Ladder",       ["ja"] = "基準はしご",          ["hi"] = "きじゅんはしご" },
            ["FrillBaseHint"]   = new() { ["en"] = "Select a ladder-shaped quad strip in the model, then import.",
                                          ["ja"] = "モデル側ではしご状につながった四角形を選択してから取り込む",
                                          ["hi"] = "しかくけいをえらんでからとりこむ" },
            ["ImportBelt"]      = new() { ["en"] = "Import Ladder from Mesh", ["ja"] = "取り込み(選択四角形→基準はしご)", ["hi"] = "とりこみ" },
            ["FrillNoBase"]     = new() { ["en"] = "(no base ladder)",  ["ja"] = "(基準はしご未取込)",  ["hi"] = "(まだとりこんでない)" },
            ["FrillBaseInfo"]   = new() { ["en"] = "Base ladder: {0} rungs ({1})", ["ja"] = "基準はしご: rung {0} ({1})", ["hi"] = "きじゅん: rung {0} ({1})" },
            ["BeltOpen"]        = new() { ["en"] = "open",              ["ja"] = "開",                 ["hi"] = "ひらき" },
            ["BeltClosed"]      = new() { ["en"] = "closed",            ["ja"] = "閉",                 ["hi"] = "とじ" },
            ["NoSelectedFaces"] = new() { ["en"] = "No selected faces", ["ja"] = "選択面がありません",  ["hi"] = "えらんでない" },
            ["ResetProfile"]    = new() { ["en"] = "Reset",             ["ja"] = "リセット",           ["hi"] = "もどす" },
            ["ResetView"]       = new() { ["en"] = "Reset View",        ["ja"] = "ビュー初期化",       ["hi"] = "ビューをもどす" },
            ["LassoMode"]       = new() { ["en"] = "Lasso",             ["ja"] = "投げ縄",             ["hi"] = "なげなわ" },
            ["FrillAxisHint"]   = new() { ["en"] = "X = travel direction (x=1 is one rung step), Y = surface normal (normalized by rail segment length).",
                                          ["ja"] = "X=進行方向（x=1 が rung 1区間） / Y=法線方向（レール区間長で正規化）",
                                          ["hi"] = "X=すすむむき（1くぎり） / Y=ほうせん" },
            ["PipeAxisHint"]    = new() { ["en"] = "X = rung direction, Y = surface normal. Normalized by rung length (x=1 is the rung length). Closed section.",
                                          ["ja"] = "X=rung方向 / Y=法線方向。rung 長で正規化（x=1 が rung の長さ）。断面は閉ループ",
                                          ["hi"] = "X=よこぎ / Y=ほうせん。とじたかたち" },
            ["PipeCapEnds"]     = new() { ["en"] = "Cap ends (open ladder only)", ["ja"] = "両端に蓋を張る（開いたはしごのみ）", ["hi"] = "はしにふたをする" },
            ["PlaceSource"]     = new() { ["en"] = "Source Object",   ["ja"] = "配置オブジェクト",   ["hi"] = "おくもの" },
            ["PlaceNoSource"]   = new() { ["en"] = "(not selected)",  ["ja"] = "(未選択)",           ["hi"] = "(みせんたく)" },
            ["PlaceRefresh"]    = new() { ["en"] = "Refresh list",    ["ja"] = "一覧を再取得",       ["hi"] = "とりなおす" },
            ["PlaceMode"]       = new() { ["en"] = "Assign Mode",     ["ja"] = "割り当て方式",       ["hi"] = "わりあてかた" },
            ["PlaceModeCombine"]  = new() { ["en"] = "Combine all",        ["ja"] = "全部を結合して配置",     ["hi"] = "ぜんぶくっつける" },
            ["PlaceModeSequence"] = new() { ["en"] = "Sequential per rung", ["ja"] = "rung ごとに順番",        ["hi"] = "よこぎごとにじゅんばん" },
            ["PlaceModeRandom"]   = new() { ["en"] = "Random per rung",     ["ja"] = "rung ごとにランダム",    ["hi"] = "よこぎごとにランダム" },
            ["PlaceSeed"]       = new() { ["en"] = "Seed",            ["ja"] = "乱数シード",         ["hi"] = "らんすうのたね" },
            ["PlaceScaleMode"]       = new() { ["en"] = "Scale Basis",        ["ja"] = "スケール方式",       ["hi"] = "おおきさのきめかた" },
            ["PlaceScaleModeRung"]   = new() { ["en"] = "Proportional to rung length", ["ja"] = "rung 長に比例", ["hi"] = "よこぎのながさにあわせる" },
            ["PlaceScaleModeUniform"] = new() { ["en"] = "Uniform size",      ["ja"] = "一律サイズ",         ["hi"] = "ぜんぶおなじおおきさ" },
            ["PlaceScaleHintRung"]   = new() { ["en"] = "Size = rung length x this value. A wider ladder makes a bigger object (1 matches the rung length).",
                                          ["ja"] = "大きさ = rung 長 × この値。梯子の幅が広いほど大きくなります（1 で rung 長と等倍）。",
                                          ["hi"] = "よこぎのながさ × このすうじ。はしごがひろいと おおきくなります。" },
            ["PlaceScaleHintUniform"] = new() { ["en"] = "Size = this value only. The ladder width does not change the size (1 keeps the source object's own size).",
                                          ["ja"] = "大きさ = この値のみ。梯子の幅は大きさに影響しません（1 で配置元そのままの大きさ）。",
                                          ["hi"] = "このすうじだけで きまります。はしごのはばは かんけいありません。" },
            ["PlaceScaleRungLabel"]    = new() { ["en"] = "Scale x",  ["ja"] = "倍率",   ["hi"] = "ばいりつ" },
            ["PlaceScaleUniformLabel"] = new() { ["en"] = "Size",     ["ja"] = "サイズ", ["hi"] = "おおきさ" },
            ["PlaceThin"]       = new() { ["en"] = "Thinning",       ["ja"] = "間引き",             ["hi"] = "まびき" },
            ["PlaceThinHint"]   = new() { ["en"] = "Places only every Nth rung and every Nth ladder row. Set the interval to 1 to place all of them.",
                                          ["ja"] = "rung と段（横につながった梯子）を何個おきに配置するかを決めます。間隔 1 で全部に配置します。段の間引きは「上下方向にも探索」が ON のときだけ効きます。",
                                          ["hi"] = "なんこおきに おくかを きめます。1 で ぜんぶにおきます。" },
            ["PlaceRungStride"] = new() { ["en"] = "Rung Interval",   ["ja"] = "rung 間隔",          ["hi"] = "よこぎのかんかく" },
            ["PlaceRungOffset"] = new() { ["en"] = "Rung Start",      ["ja"] = "rung 開始位置",      ["hi"] = "よこぎのはじまり" },
            ["PlaceRowStride"]  = new() { ["en"] = "Row Interval",    ["ja"] = "段 間隔",            ["hi"] = "だんのかんかく" },
            ["PlaceRowOffset"]  = new() { ["en"] = "Row Start",       ["ja"] = "段 開始位置",        ["hi"] = "だんのはじまり" },
            ["PlaceRungLenInfo"] = new() { ["en"] = "Rung length: min {0} / max {1} / avg {2}",
                                          ["ja"] = "rung 長: 最小 {0} / 最大 {1} / 平均 {2}",
                                          ["hi"] = "よこぎのながさ: {0} 〜 {1}（へいきん {2}）" },
            ["PlaceCountInfo"]  = new() { ["en"] = "Placed: {0} on {1} row(s)",
                                          ["ja"] = "配置個数: {0} 個 / 対象 {1} 段",
                                          ["hi"] = "おくかず: {0} こ / {1} だん" },
            ["NoSourceObject"]  = new() { ["en"] = "No source object", ["ja"] = "対象オブジェクト未選択", ["hi"] = "たいしょうがない" },
            ["AutoDetectSource"] = new() { ["en"] = "Auto Detect Target", ["ja"] = "自動検索の対象",   ["hi"] = "じどうけんさく" },
            ["AutoDetectBelts"] = new() { ["en"] = "Auto Detect Ladders", ["ja"] = "はしごを自動検索",  ["hi"] = "はしごをさがす" },
            ["AutoDetectHint"]  = new() { ["en"] = "Starts at a start tag triangle (shares no edge, touches the mesh at exactly one vertex) and walks the quad strip from the tip triangles around that vertex.",
                                          ["ja"] = "開始タグの三角形（辺を共有せず、頂点1個だけでモデルに接する三角形）を起点にし、その頂点に接する先端三角形から四角形列を辿る",
                                          ["hi"] = "かいしタグのさんかくからさがす" },
            ["AutoDetectRings"] = new() { ["en"] = "Auto Detect Rings", ["ja"] = "円環を自動検索",  ["hi"] = "わっかをさがす" },
            ["AutoDetectRingsHint"] = new() { ["en"] = "Finds every quad strip that loops back on itself. When two directions both close, the one found first wins.",
                                          ["ja"] = "対辺を辿って一周する四角形列を全部探す。直交する2方向とも閉じる形状では先に見つかった側を採る",
                                          ["hi"] = "ひとまわりするしかくけいをさがす" },
            ["BeltsInfo"]       = new() { ["en"] = "Ladders: {0} ({1} rungs)", ["ja"] = "基準はしご: {0} 本 (rung 合計 {1})", ["hi"] = "はしご {0} ほん" },
            ["BeltsInfoG"]      = new() { ["en"] = "Ladders: {0} in {1} group(s) ({2} rungs)",
                                          ["ja"] = "基準はしご: {0} 段 / {1} グループ (rung 合計 {2})",
                                          ["hi"] = "はしご {0} だん / {1} グループ" },
            ["BeltStackSearch"] = new() { ["en"] = "Also search up/down", ["ja"] = "上下方向にも探索", ["hi"] = "うえしたもさがす" },
            ["BeltStackSearchHint"] = new() { ["en"] = "After finding a ladder, crosses its rail edges to pick up the ladders stacked above and below. Stops at a free edge, a triangle, or a face already taken.",
                                          ["ja"] = "見つけた梯子のレール辺を跨いで、上下に並ぶ梯子も取り込む。自由辺・三角形・使用済みの面で止まる。取り込み・自動検索・円環検索のすべてに効く",
                                          ["hi"] = "はしごのうえしたにつながるはしごもとりこむ" },
            ["FrillHeightScale"] = new() { ["en"] = "Height Scale",   ["ja"] = "高さ倍率",   ["hi"] = "たかさのばい" },
            ["FrillHeightScaleHint"] = new() { ["en"] = "Scales only the surface-normal component of the profile (profile Y). 1 keeps the original height; 0 flattens it to the base ladder.",
                                          ["ja"] = "断面プロファイルの法線方向成分（プロファイル Y）だけを倍率で伸縮する。1＝そのまま / 0＝基準はしごと同じ平坦",
                                          ["hi"] = "たかさだけかえる。1でそのまま / 0でたいら" },
            ["FrillBeltScales"] = new() { ["en"] = "Height Scale per Ladder", ["ja"] = "はしごごとの高さ倍率", ["hi"] = "はしごごとのたかさ" },
            ["FrillBeltScalesHint"] = new() { ["en"] = "Multiplied with the overall height scale. Where belts share a rail segment, the scales of the contributing belts are averaged.",
                                          ["ja"] = "全体の高さ倍率と掛け算になる。レール線分を共有する部分では、寄与したはしごの倍率を平均する",
                                          ["hi"] = "ぜんたいのばいりつとかけざん" },
            ["FrillBeltScaleRow"] = new() { ["en"] = "Ladder {0} (rungs {1})", ["ja"] = "はしご {0} (rung {1})", ["hi"] = "はしご {0} ({1})" },
            ["FrillGroupScaleRow"] = new() { ["en"] = "Group {0} ({1} rows / {2} rungs)", ["ja"] = "グループ {0} (段 {1} / rung 合計 {2})", ["hi"] = "グループ {0} ({1}だん)" },
            ["FrillTwoProfiles"] = new() { ["en"] = "Two profiles (A / B)", ["ja"] = "断面プロファイルを2本にする(A/B)", ["hi"] = "だんめんを2ほんにする" },
            ["FrillTwoProfilesHint"] = new() { ["en"] = "A is applied to the t=0 rail of a stack, B to the t=1 rail, and rows in between are interpolated linearly. With a single ladder, A goes to the left rail and B to the right. If the point counts differ, the shorter profile is used for both.",
                                          ["ja"] = "段グループの t=0 側レールに A、t=1 側レールに B を当て、中間の段は線形補間する。段が1本なら左レールがA・右レールがB。点数が違うときは点数の少ない側を両方に使う",
                                          ["hi"] = "うえがA・したがB。あいだはすこしずつまぜる" },
            ["FrillProfileFlip"] = new() { ["en"] = "Flip A/B (up-down)", ["ja"] = "上下フリップ(A/B入替)", ["hi"] = "うえしたいれかえ" },
            ["FrillProfileFlipHint"] = new() { ["en"] = "Which side is up cannot be decided from the geometry, so flip here if A and B come out the wrong way round.",
                                          ["ja"] = "どちらが上かは形状から決められないため、A/Bが逆に出たらここで入れ替える",
                                          ["hi"] = "AとBがぎゃくなときにつかう" },
            ["FrillProfileTarget"] = new() { ["en"] = "Editing", ["ja"] = "編集対象", ["hi"] = "へんしゅうするほう" },
            ["FrillProfileA"]   = new() { ["en"] = "A", ["ja"] = "A", ["hi"] = "A" },
            ["FrillProfileB"]   = new() { ["en"] = "B", ["ja"] = "B", ["hi"] = "B" },
            ["FrillProfileGhostHint"] = new() { ["en"] = "The other profile is drawn in grey for reference.",
                                          ["ja"] = "編集していない側は灰色で重ねて表示する",
                                          ["hi"] = "もういっぽうは はいいろでみえる" },
            ["FrillConnect"]    = new() { ["en"] = "Connect Shared Rails", ["ja"] = "共有レールをつなげる", ["hi"] = "つなげる" },
            ["FrillConnectHint"]= new() { ["en"] = "Welds ladders that share the same rail segment (left/right when upright, top/bottom when sideways) and averages the normal at the seam.",
                                          ["ja"] = "同じレール線分（縦置きなら左右、横置きなら上下）を共有するはしごどうしを溶接し、継ぎ目の法線を平均する",
                                          ["hi"] = "おなじへりをもつはしごをくっつける" },
            ["FrillRungSeam"]   = new() { ["en"] = "Step at rung seams", ["ja"] = "rung境界に段差をつける", ["hi"] = "つぎめにだんさ" },
            ["FrillRungSeamHint"]= new() { ["en"] = "Off: averages the end of one step and the start of the next into one vertex. On: keeps both, so the seam steps.",
                                          ["ja"] = "OFF＝ステップ終端と次ステップ始端を平均して1頂点にまとめる / ON＝2頂点のまま残して段差を出す",
                                          ["hi"] = "ONにするとつぎめがずれる" },
            ["BeltCsv"]         = new() { ["en"] = "Ladder CSV",  ["ja"] = "はしごCSV",   ["hi"] = "はしごCSV" },
            ["ProfileCsv"]      = new() { ["en"] = "Profile CSV", ["ja"] = "断面CSV",   ["hi"] = "だんめんCSV" },
            ["BeltOrient"]      = new() { ["en"] = "Ladder Orientation", ["ja"] = "はしごの向き", ["hi"] = "はしごのむき" },
            ["BeltSwapSides"]   = new() { ["en"] = "Swap left/right", ["ja"] = "左右を入れ替える", ["hi"] = "さゆうをいれかえる" },
            ["BeltReverseOrder"]= new() { ["en"] = "Reverse rung order", ["ja"] = "rung 順を反転する", ["hi"] = "じゅんばんをぎゃくにする" },
            ["BeltOrientHint"]  = new() { ["en"] = "Left/right swap turns placed objects 180 degrees about the rung normal. Reversing rung order flips the profile end for end. Faces never invert.",
                                          ["ja"] = "左右入替は配置オブジェクトを rung 法線まわりに180°回す / rung順反転は断面プロファイルの向きが端から端へ入れ替わる。いずれも面は裏返らない",
                                          ["hi"] = "むきをかえる。うらがえりはしない" },
            ["BeltSpline"]      = new() { ["en"] = "Spline Subdivision", ["ja"] = "スプライン分割", ["hi"] = "スプラインぶんかつ" },
            ["BeltSplineHint"]  = new() { ["en"] = "Interpolates both rails with a cubic spline to increase the rung count.",
                                          ["ja"] = "左右レールを3次スプラインで補間して段数を増やす",
                                          ["hi"] = "だんすうをふやす" },
            ["BeltSplineEnable"]    = new() { ["en"] = "Enable",            ["ja"] = "有効",             ["hi"] = "ゆうこう" },
            ["BeltSplineSegs"]      = new() { ["en"] = "Steps per Segment", ["ja"] = "段間の補間数",     ["hi"] = "あいだのかず" },
            ["BeltSplineUseFirst"]  = new() { ["en"] = "Use Start Tip",     ["ja"] = "開始端を利用",     ["hi"] = "はじめをつかう" },
            ["BeltSplineUseLast"]   = new() { ["en"] = "Use End Tip",       ["ja"] = "終了端を利用",     ["hi"] = "おわりをつかう" },
            ["BeltSplineTrimStart"] = new() { ["en"] = "Trim Start",        ["ja"] = "先頭を削る段数",   ["hi"] = "はじめをけずる" },
            ["BeltSplineTrimEnd"]   = new() { ["en"] = "Trim End",          ["ja"] = "末尾を削る段数",   ["hi"] = "おわりをけずる" },
            ["PlaceBaseHint"]   = new() { ["en"] = "One object per rung. Rung center is the position, rung length is the scale, and the face normal is +Z.",
                                          ["ja"] = "rung ごとに1個。位置=rung 中心、倍率=rung 長、面法線=+Z",
                                          ["hi"] = "よこぎごとに1こおく" },

            // ── リボン ──
            ["RibbonHint"]      = new() { ["en"] = "Generates the bow as quad-strip ladders (2 loops, 2 tails, 1 knot band). No thickness or cross-section: feed it to Frill / Pipe as a base belt.",
                                          ["ja"] = "蝶結びを梯子（ループ2・テール2・ノット1）として生成します。厚みと断面は付けないので、フリル／パイプの基準ベルトとして使ってください。",
                                          ["hi"] = "ちょうむすびを はしごでつくります。あつみはつきません。" },
            ["RibbonWidth"]     = new() { ["en"] = "Ribbon Width",  ["ja"] = "帯の幅",        ["hi"] = "おびのはば" },
            ["RibbonParts"]     = new() { ["en"] = "Parts",         ["ja"] = "部品",          ["hi"] = "ぶひん" },
            ["RibbonPartsHint"] = new() { ["en"] = "Turn parts off to build a multi-layer bow in several passes: generate once without the loops, once with them, then merge the objects with another tool.",
                                          ["ja"] = "多重リボンは部品を切り替えて複数回に分けて作ります。1回目はループ抜き、2回目はループ付きで生成し、別のツールで結合してください。",
                                          ["hi"] = "ぶひんをきりかえて なんかいかにわけてつくり、あとでくっつけます。" },
            ["RibbonBuildLoops"] = new() { ["en"] = "Build Loops",   ["ja"] = "ループを作る",  ["hi"] = "ループをつくる" },
            ["RibbonBuildTails"] = new() { ["en"] = "Build Tails",   ["ja"] = "テールを作る",  ["hi"] = "テールをつくる" },
            ["RibbonBuildKnot"]  = new() { ["en"] = "Build Knot",    ["ja"] = "ノットを作る",  ["hi"] = "ノットをつくる" },
            ["RibbonLoop"]      = new() { ["en"] = "Loop",          ["ja"] = "ループ",        ["hi"] = "ループ" },
            ["RibbonLoopFlip"]  = new() { ["en"] = "Flip faces at the fold", ["ja"] = "折り返しで面を裏返す", ["hi"] = "おりかえしでうらがえす" },
            ["RibbonLoopFlipHint"] = new() { ["en"] = "On: the real ribbon shape. The loop is a flat tube - the outgoing layer in front, the returning layer behind - and the face changes over at the fold, so the returning layer shows its back side. Off: the front side faces you along the whole loop (shoelace-like). Neither twists the strip.",
                                          ["ja"] = "ON は実物のリボン。往路が手前・復路が奥の平たい筒になり、折り返しの1箇所で面が入れ替わるので復路は裏面が正面を向きます。OFF はループの全長で表が正面を向きます（靴紐など）。どちらも帯はねじれません。",
                                          ["hi"] = "ONだと おりかえしで うらがみえます。OFFは ずっとおもてです。ねじれません。" },
            ["RibbonLoopWidth"] = new() { ["en"] = "Loop Width",    ["ja"] = "ループの張り出し", ["hi"] = "ループのはりだし" },
            ["RibbonLoopHeight"] = new() { ["en"] = "Loop Height",  ["ja"] = "ループの高さ",  ["hi"] = "ループのたかさ" },
            ["RibbonLoopSag"]   = new() { ["en"] = "Loop Sag",      ["ja"] = "ループの下がり", ["hi"] = "ループのさがり" },
            ["RibbonLoopTilt"]  = new() { ["en"] = "Loop Tilt (deg)", ["ja"] = "ループの回転(度)", ["hi"] = "ループのかいてん" },
            ["RibbonLoopTiltHint"] = new() { ["en"] = "Rotates the whole loop about its root. Positive lifts the outer end on both sides. Loop Sag can only pull the fold down, so use this when the fold has to sit above the knot.",
                                          ["ja"] = "ループ全体を根元を中心に回します。正で左右とも外側が上がります。「ループの下がり」は折り返しを下げることしかできないので、折り返しをノットより上に置きたいときはこちらを使ってください。",
                                          ["hi"] = "ループぜんたいを ねもとをちゅうしんに まわします。プラスで そとがわがあがります。" },
            ["RibbonLoopDepth"] = new() { ["en"] = "Loop Depth (Z)", ["ja"] = "ループの厚み(Z)", ["hi"] = "ループのあつみ" },
            ["RibbonLoopDepthHint"] = new() { ["en"] = "Flip on: half the gap between the outgoing and returning layers, which is also the radius of the fold. Flip off: how far the loop bulges toward the front.",
                                          ["ja"] = "裏返す ON では往路と復路の間隔の半分＝折り返しの半径です。OFF ではループが手前へ膨らむ量です。",
                                          ["hi"] = "ONでは おうふくのあいだ、OFFでは てまえへのふくらみ。" },
            ["RibbonRootGap"]   = new() { ["en"] = "Root Gap",      ["ja"] = "根元の間隔",    ["hi"] = "ねもとのあいだ" },
            ["RibbonRootPinch"] = new() { ["en"] = "Root Pinch",    ["ja"] = "根元の絞り",    ["hi"] = "ねもとをほそく" },
            ["RibbonTail"]      = new() { ["en"] = "Tail",          ["ja"] = "テール",        ["hi"] = "テール" },
            ["RibbonTailLength"] = new() { ["en"] = "Tail Length",  ["ja"] = "テールの落差",  ["hi"] = "テールのながさ" },
            ["RibbonTailSpread"] = new() { ["en"] = "Tail Spread",  ["ja"] = "テールの開き",  ["hi"] = "テールのひらき" },
            ["RibbonTailClose"] = new() { ["en"] = "Tail Close",    ["ja"] = "テールの閉じ",  ["hi"] = "テールのとじ" },
            ["RibbonTailCloseAt"] = new() { ["en"] = "Close Start", ["ja"] = "閉じ始める位置", ["hi"] = "とじはじめるところ" },
            ["RibbonTailCloseHint"] = new() { ["en"] = "Tail Spread opens the tail outward. Close pulls the tip back toward the centre from the widest point: 0 keeps it fully open, 1 brings it back to the root. Close Start is where that widest point sits (0 = root, 1 = tip). Close 0 keeps the previous shape exactly.",
                                          ["ja"] = "「テールの開き」で外へ開いた形から、最大開き点より先を中央側へ戻します。0 で戻さない（従来の形）、1 で根元と同じ位置まで戻ります。「閉じ始める位置」は最大開き点の縦位置（0=根元 / 1=先端）です。",
                                          ["hi"] = "そとへひらいたあと、さきっぽを まんなかへもどします。0でもどさない、1でねもとまで。" },
            ["RibbonTailSag"]   = new() { ["en"] = "Tail Sag",      ["ja"] = "テールの曲がり", ["hi"] = "テールのまがり" },
            ["RibbonTailDepth"] = new() { ["en"] = "Tail Depth",    ["ja"] = "テールの膨らみ(Z)", ["hi"] = "テールのふくらみ" },
            ["RibbonTailTaper"] = new() { ["en"] = "Tail Taper",    ["ja"] = "先端の幅倍率",  ["hi"] = "さきのはば" },
            ["RibbonKnot"]      = new() { ["en"] = "Knot",          ["ja"] = "ノット",        ["hi"] = "ノット" },
            ["RibbonKnotHint"]  = new() { ["en"] = "The knot is one short vertical ladder that covers the roots.",
                                          ["ja"] = "ノットは根元を覆う短い縦向きの梯子1本です。",
                                          ["hi"] = "ノットは みじかいはしご1ほんです。" },
            ["RibbonKnotWidth"] = new() { ["en"] = "Knot Width",    ["ja"] = "ノットの幅",    ["hi"] = "ノットのはば" },
            ["RibbonKnotHeight"] = new() { ["en"] = "Knot Height",  ["ja"] = "ノットの長さ",  ["hi"] = "ノットのながさ" },
            ["RibbonKnotDepth"] = new() { ["en"] = "Knot Depth",    ["ja"] = "ノットの膨らみ(Z)", ["hi"] = "ノットのふくらみ" },
            ["RibbonLoopSegs"]  = new() { ["en"] = "Loop Steps",    ["ja"] = "ループの分割数", ["hi"] = "ループのぶんかつ" },
            ["RibbonTailSegs"]  = new() { ["en"] = "Tail Steps",    ["ja"] = "テールの分割数", ["hi"] = "テールのぶんかつ" },
            ["RibbonKnotSegs"]  = new() { ["en"] = "Knot Steps",    ["ja"] = "ノットの分割数", ["hi"] = "ノットのぶんかつ" },
            ["RibbonTags"]      = new() { ["en"] = "Ladder Tags",   ["ja"] = "梯子タグ",      ["hi"] = "はしごのめじるし" },
            ["RibbonTagsHint"]  = new() { ["en"] = "The start tag is the marker that Frill / Pipe auto-detect looks for. It only works when the start tip triangle exists, so turning the tag on turns the tip on as well.",
                                          ["ja"] = "開始タグはフリル／パイプの自動検索が探す目印です。開始三角が無いと成立しないため、タグを付けると開始三角も自動で付きます。",
                                          ["hi"] = "はじまりのめじるしです。かいしさんかくもいっしょにつきます。" },
            ["RibbonStartTag"]  = new() { ["en"] = "Start Tag Triangle", ["ja"] = "開始タグ三角を付ける", ["hi"] = "はじまりのめじるし" },
            ["RibbonStartTip"]  = new() { ["en"] = "Start Tip Triangle", ["ja"] = "開始三角を付ける",     ["hi"] = "はじまりのさんかく" },
            ["RibbonEndTip"]    = new() { ["en"] = "End Tip Triangle",   ["ja"] = "終了三角を付ける",     ["hi"] = "おわりのさんかく" },
            ["RibbonTipLen"]    = new() { ["en"] = "Tip Length",    ["ja"] = "先端三角の長さ", ["hi"] = "さんかくのながさ" },
            ["RibbonTagSize"]   = new() { ["en"] = "Tag Size",      ["ja"] = "タグ三角の大きさ", ["hi"] = "めじるしのおおきさ" },

            // ── 簡易歯車 / スタア / インボリュート歯車 共通 ──
            ["GearToothCount"]  = new() { ["en"] = "Teeth",         ["ja"] = "歯の数",        ["hi"] = "はのかず" },
            ["GearInnerRadius"] = new() { ["en"] = "Valley Radius", ["ja"] = "谷の半径",      ["hi"] = "たにのはんけい" },
            ["GearOuterRadius"] = new() { ["en"] = "Tip Radius",    ["ja"] = "歯先の半径",    ["hi"] = "はさきのはんけい" },
            ["GearAngles"]      = new() { ["en"] = "Tooth Angles",  ["ja"] = "歯の角度",      ["hi"] = "はのかくど" },
            ["GearThetaL"]      = new() { ["en"] = "Tip Width θL",  ["ja"] = "歯先の幅 θL",   ["hi"] = "はさきのはば" },
            ["GearThetaM"]      = new() { ["en"] = "Slope θM",      ["ja"] = "傾斜部 θM",     ["hi"] = "ななめのぶぶん" },
            ["GearRotationOffset"] = new() { ["en"] = "Rotation Offset", ["ja"] = "回転オフセット", ["hi"] = "かいてん" },
            ["GearBore"]        = new() { ["en"] = "Center Bore",   ["ja"] = "中心の穴",      ["hi"] = "まんなかのあな" },
            ["GearBoreRadius"]  = new() { ["en"] = "Bore Radius",   ["ja"] = "穴の半径",      ["hi"] = "あなのはんけい" },
            ["GearBoreSegments"] = new() { ["en"] = "Bore Segments", ["ja"] = "穴の分割数",    ["hi"] = "あなのぶんかつ" },
            ["GearBoreHint"]    = new() { ["en"] = "0 makes a solid disk. The bore is clamped below the smallest outline radius.",
                                          ["ja"] = "0 で穴なしになります。輪郭の最小半径を超える指定は自動で内側へ抑えます。",
                                          ["hi"] = "0 なら あなをあけません。おおきすぎるあなは じどうでちいさくします。" },
            ["NGonGearHint"]    = new() { ["en"] = "A gear made of trapezoidal teeth defined by angles. The tooth outline is extruded along the plane normal.",
                                          ["ja"] = "角度で歯の形を決める簡易な歯車です。輪郭をそのまま厚み方向へ押し出します。",
                                          ["hi"] = "かくどで はのかたちをきめる かんたんなはぐるまです。" },
            ["GearThetaSInfo"]  = new() { ["en"] = "Valley width θS = {0}° (auto) / tooth pitch {1}°",
                                          ["ja"] = "谷の幅 θS = {0}°（自動計算） / 1歯ぶんの角度 {1}°",
                                          ["hi"] = "たにのはば θS = {0}°（じどう） / 1はぶん {1}°" },
            ["NGonStarHint"]    = new() { ["en"] = "Alternates the tip radius and the valley radius at even angles.",
                                          ["ja"] = "外径と内径を等角度で交互に置いた星型です。",
                                          ["hi"] = "そとがわとうちがわを こうごにおいた ほしのかたちです。" },
            ["StarPoints"]      = new() { ["en"] = "Points",        ["ja"] = "尖りの数",      ["hi"] = "とがりのかず" },
            ["StarInnerRadius"] = new() { ["en"] = "Valley Radius", ["ja"] = "谷の半径",      ["hi"] = "たにのはんけい" },
            ["StarOuterRadius"] = new() { ["en"] = "Point Radius",  ["ja"] = "尖りの半径",    ["hi"] = "とがりのはんけい" },

            // ── インボリュート歯車 ──
            ["InvoluteGearHint"] = new() { ["en"] = "Involute flanks with a trochoidal root generated by a sharp rack cutter corner. Undercut is represented automatically at low tooth counts.",
                                          ["ja"] = "歯面はインボリュート曲線、歯元は尖ったラックカッタの角が描くトロコイド曲線です。歯数が少ないときは切り下げ（アンダーカット）を自動で表現します。",
                                          ["hi"] = "はのかたちを けいさんでつくる ほんかくてきなはぐるまです。" },
            ["InvToothCount"]   = new() { ["en"] = "Teeth z",       ["ja"] = "歯数 z",        ["hi"] = "はのかず" },
            ["InvModule"]       = new() { ["en"] = "Module m",      ["ja"] = "モジュール m",  ["hi"] = "おおきさのもと" },
            ["InvPressureAngle"] = new() { ["en"] = "Pressure Angle α", ["ja"] = "圧力角 α",  ["hi"] = "あつりょくかく" },
            ["InvCorrection"]   = new() { ["en"] = "Correction",    ["ja"] = "転位・バックラッシ", ["hi"] = "ずらし" },
            ["InvCorrectionHint"] = new() { ["en"] = "Profile shift moves the rack cutter radially. Backlash thins the tooth at the pitch circle.",
                                          ["ja"] = "転位係数はラックカッタを半径方向へずらします。バックラッシはピッチ円上の歯厚を細らせます。",
                                          ["hi"] = "はのふとさと いちを かえます。" },
            ["InvProfileShift"] = new() { ["en"] = "Profile Shift x", ["ja"] = "転位係数 x",  ["hi"] = "ずらしのりょう" },
            ["InvBacklash"]     = new() { ["en"] = "Backlash",      ["ja"] = "バックラッシ",  ["hi"] = "すきま" },
            ["InvSampling"]     = new() { ["en"] = "Curve Sampling", ["ja"] = "曲線の分割数", ["hi"] = "きょくせんのぶんかつ" },
            ["InvTrochoidSamples"] = new() { ["en"] = "Trochoid / flank", ["ja"] = "トロコイド分割", ["hi"] = "はもとのぶんかつ" },
            ["InvInvoluteSamples"] = new() { ["en"] = "Involute / flank", ["ja"] = "インボリュート分割", ["hi"] = "はめんのぶんかつ" },
            ["InvTipArcSamples"] = new() { ["en"] = "Tip Arc",      ["ja"] = "歯先円弧の分割", ["hi"] = "はさきのぶんかつ" },
            ["InvRootArcSamples"] = new() { ["en"] = "Root Arc",    ["ja"] = "歯元円弧の分割", ["hi"] = "はもとのえんこ" },
            ["InvDerived"]      = new() { ["en"] = "Derived Dimensions", ["ja"] = "派生諸元", ["hi"] = "けいさんけっか" },
            ["InvDerivedInfo"]  = new() { ["en"] = "Pitch Ø {0} / Base Ø {1} / Tip Ø {2} / Root Ø {3}\nCircular pitch {4} / Tooth thickness {5} / Join r {6}",
                                          ["ja"] = "ピッチ円直径 {0} / 基礎円直径 {1} / 歯先円直径 {2} / 歯元円直径 {3}\n円ピッチ {4} / ピッチ円上歯厚 {5} / 接続半径 {6}",
                                          ["hi"] = "ちょっけい {0} / きそ {1} / はさき {2} / はもと {3}\nピッチ {4} / はあつ {5} / つなぎめ {6}" },
            ["InvInvalid"]      = new() { ["en"] = "The current parameters do not give a valid gear (check module, profile shift and backlash).",
                                          ["ja"] = "現在の値では歯車が成立しません（モジュール・転位係数・バックラッシを見直してください）。",
                                          ["hi"] = "いまのすうじでは はぐるまになりません。" },
            ["InvWarnMinTeeth"] = new() { ["en"] = "At α={0}°, z={1} is below the approximate no-undercut limit z≈{2}.",
                                          ["ja"] = "圧力角 {0}° では、歯数 {1} は切り下げ限界の目安 z≈{2} を下回っています。",
                                          ["hi"] = "α={0}° では はのかず {1} は すくなすぎます（めやす z≈{2}）。" },
            ["InvWarnUndercut"] = new() { ["en"] = "Undercut: the rack corner cuts away the lower involute, so that part is removed automatically.",
                                          ["ja"] = "切り下げが起きています。ラックの角が下側のインボリュートを削るため、その部分を自動で取り除いています。",
                                          ["hi"] = "はのねもとが けずれています。" },
            ["InvWarnSevereUndercut"] = new() { ["en"] = "Severe undercut: almost no involute flank remains. Increase the tooth count or use a positive profile shift.",
                                          ["ja"] = "切り下げが激しく、インボリュート歯面がほとんど残りません。歯数を増やすか、転位係数を正にしてください。",
                                          ["hi"] = "けずれすぎです。はのかずをふやしてください。" },
            ["InvWarnBore"]     = new() { ["en"] = "Bore radius reaches the root circle; it is clamped inside automatically.",
                                          ["ja"] = "穴の半径が歯元円に達しています。自動で内側へ抑えます。",
                                          ["hi"] = "あなが おおきすぎます。じどうでちいさくします。" },
        };

        public static string T(string key) => L.GetFrom(Texts, key);
        public static string T(string key, params object[] args) => L.GetFrom(Texts, key, args);
    }
}
